apiVersion: sso.apps.tanzu.vmware.com/v1alpha1
kind: ClientRegistration
metadata:
  name: customer-profile-ui-client-registration
spec:
  authServerSelector:
    matchLabels:
      name: 'my-first-auth-server'
  authorizationGrantTypes:
    - authorization_code
    - refresh_token
  clientAuthenticationMethod: basic
  requireUserConsent: false
  redirectURIs:
    - http://customer-profile-ui.my-apps.tap.desktop-scenarios.tapdemo.vmware.com/login/oauth2/code/customer-profile-ui
  scopes:
    - name: openid
